# Generated by Django 5.0 on 2024-05-07 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_19', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
