# Generated by Django 5.0 on 2024-05-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_19', '0004_remove_profile_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
