# Generated by Django 5.0 on 2024-05-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_19', '0007_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
