# Generated by Django 5.0 on 2024-05-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_19', '0010_report_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='doctor_report',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='patient_report',
            field=models.TextField(blank=True),
        ),
    ]
